const page = Number(document.body.dataset.page || 1);
const key = 'spacePlanetProgress';
let progress = Number(localStorage.getItem(key) || 1);
function dots(){document.querySelectorAll('.dot').forEach((d,i)=>d.className='dot '+(i+1<page?'done':i+1===page?'current':''));}
function showUnlocked(){document.body.classList.add('planet-unlocked');document.querySelectorAll('[data-next]').forEach(x=>x.classList.add('primary'));document.querySelector('#try-again')?.classList.remove('show');document.querySelector('#answer')?.classList.add('show');}
function complete(){progress=Math.max(progress,page+1);localStorage.setItem(key,progress);showUnlocked();}
function locked(){if(page>progress){document.querySelector('main').innerHTML=`<section class="card locked"><div class="lock">🔒</div><h1>Planet locked!</h1><p>Complete the earlier planet mission first. Each success prepares you for a harder challenge.</p><a class="button primary" href="page${progress}.html">Return to my mission</a></section>`;return true;}return false;}
function choices(){const all=document.querySelectorAll('.choice');all.forEach(c=>c.onclick=()=>{if(document.body.classList.contains('planet-unlocked'))return;all.forEach(x=>x.classList.remove('selected','incorrect'));c.classList.add('selected');if(c.dataset.correct==='true')complete();else{c.classList.add('incorrect');document.querySelector('#try-again')?.classList.add('show');}})}
function ship(){const drag=document.querySelectorAll('[draggable=true]'),zone=document.querySelector('#ship'),order=['nose','body','fin','engine'];drag.forEach(x=>x.ondragstart=e=>e.dataTransfer.setData('text',x.dataset.part));if(!zone)return;zone.ondragover=e=>{e.preventDefault();zone.classList.add('over')};zone.ondragleave=()=>zone.classList.remove('over');zone.ondrop=e=>{e.preventDefault();zone.classList.remove('over');let p=e.dataTransfer.getData('text');if(p!==order[zone.querySelectorAll('.placed').length]){document.querySelector('#try-again')?.classList.add('show');return;}if(!zone.querySelector(`[data-placed="${p}"]`)){let el=document.createElement('span');el.className='placed';el.dataset.placed=p;el.textContent={nose:'🔺',body:'🛸',engine:'🔥',fin:'🔻'}[p];zone.append(el)}if(zone.querySelectorAll('.placed').length===4)complete()}}
function trajectory(){const speed=document.querySelector('#speed'),angle=document.querySelector('#angle');if(!speed||!angle)return;let draw=()=>{let s=+speed.value,a=+angle.value;document.querySelector('#speedV').textContent=s;document.querySelector('#angleV').textContent=a;let peak=Math.round(s*Math.sin(a*Math.PI/180)/2);document.querySelector('#peak').textContent=peak;document.querySelector('#curve').setAttribute('d',`M 15 200 Q 125 ${200-peak} 260 200`)};speed.oninput=angle.oninput=draw;draw();document.querySelector('#solve').onclick=()=>{if(+speed.value>=70&&+angle.value>=55)complete();else document.querySelector('#try-again')?.classList.add('show');}}
function checklist(){const boxes=document.querySelectorAll('.mission-check input');boxes.forEach(b=>b.onchange=()=>{if([...boxes].filter(x=>x.checked).length===3)complete()})}
document.addEventListener('DOMContentLoaded',()=>{dots();if(locked())return;if(progress>page)showUnlocked();choices();ship();trajectory();checklist();});
